version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn: # (=nginx.conf 에서 정의한 이름)
    image: django_image:5
    networks:
      - network
    volumes:
      - static-volume:/home/pinterest/staticfiles
      - media-volume:/home/pinterest/media
    secrets:
      - MARIADB_PASSWORD
      - DJANGO_SECRET_KEY
  mariadb: # (=deploy.py 에서 DATABASES.default.HOST 에서 정의한 이름)
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql # https://hub.docker.com/_/mariadb --> Caveats
    secrets:
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment: # " --> Environment Variables, Docker Secrets
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
